### PR TITLE
UINV-357 Invoice: Error message does not indicate what Fund does not have money

### PR DESCRIPTION
**Pull request by AndreiShumski2**
## Purpose
https://issues.folio.org/browse/UINV-357

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [x] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [x] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Review by usavkov-epam — APPROVED** [review]

**Review by NikitaSedyx — APPROVED** [review]

**Comment by AndreiShumski2** [comment]
@dltj update translations please

**Comment by dltj** [comment]
In progress: https://github.com/folio-org/ui-invoice/pull/558

**Comment by AndreiShumski2** [comment]
> In progress: #558

there are no latest updates from [en.json](https://github.com/folio-org/ui-invoice/pull/556/files#diff-5fa02ad68d43f345d6ef8d90592bc3142f99bb78da756a2d344f8dcaa06973d2R308) 😔

**Comment by dltj** [comment]
Odd! Lokalise didn't automatically pick up the changes from GitHub. I forced a manual refresh.  Is this what you were expecting? https://github.com/folio-org/ui-invoice/pull/559

**Comment by dltj** [comment]
Oh, dear...Jenkins logged errors when trying to run the tests.  I don't _think_ this is coming from the translation change.  Can you review and offer some advice?  https://jenkins-aws.indexdata.com/blue/organizations/jenkins/folio-org%2Fui-invoice/detail/PR-559/1/pipeline

**Comment by AndreiShumski2** [comment]
@dltj I've updated test snapshots [(#560)](https://github.com/folio-org/ui-invoice/pull/560)

**Comment by dltj** [comment]
Ah, very good...all set: https://github.com/folio-org/ui-invoice/pull/561 — thanks!

**Pull request merged**
